### ISSUE TITLE
class Nameについて

### ISSUE THREAD

**Issue by matsumoto777** [YuukiHirama/Task0#1]
```
class Name:NSObject{
    var id:Int
    var name:String

    init(data: (Int,String)){
        id = data.0
        name = data.1
    }
}
```

1) NSObjectを継承しているのはなぜでしたっけ？

2) mutableになっていますがこれは意図的ですか？
つまり、メンバ変数がvarになっており後で外から書き換え可能になっていますが、書き換えられる必要があるでしょうか？
また、このクラスを利用する箇所は、書き換えられることを前提として整合性を取らねばならないと思いますが、そのようになっているでしょうか？
ということです。

3) コンストラクタにTupleで渡していますが、これは意図的ですか？
普通に考えたら、```init( id:Int, name:String )```となると思いますが。

**Comment by YuukiHirama** [comment]
不要な継承をしていたので削除
verからletに変更
タプルを使用せずにクラスを実装
を致しました。
9c03120

**Comment by matsumoto777** [comment]
NameModelCellのメンバ変数、先頭大文字になってますがSwiftの命名規則と合致しないので先頭小文字でお願いします。

もし、引数と同名だから、という理由でそうしたなら下記の手法で回避できます。
```
    // 方法1
    init( id:Int, name:String ){
        self.id = id
        self.name = name
    }

    // 方法2
    init( hoge id:Int, fuga name:String ){ // もしかしたら( id hoge:Int, name fuga:String )かも
        id = hoge
        name = fuga
    }
```

**Comment by YuukiHirama** [comment]
メンバ変数、先頭大文字を小文字へ修正致しました。
bf9e1ae

**Comment by matsumoto777** [comment]
OKです
