### ISSUE TITLE
追加案件：セル表示

### ISSUE THREAD

**Issue by matsumoto777** [YuukiHirama/Task0#4]
セルにNameだけでなくidも表示するようにしてみてもらえませんか。
文字列として連結するのではなく、別々のラベルにお願いします。

**Comment by YuukiHirama** [comment]
カスタムセルを追加し２列表示致しました。
44167ca

**Comment by matsumoto777** [comment]
OKなのですが、一箇所
```
nameCell.id.text = allName[indexPath.row].Id.description
```

descriptionは使わないでString(xx)を使ってほしいです。
（JavaやC#のtoStringもそうですが）iOSのdescriptionもあまり信用すべきできなく、専用のものがあればそちらを使う方が後々問題が少ないです。

**Comment by YuukiHirama** [comment]
descriptionを使わずString(x) を使用するように修正しました
f3901eb

**Comment by YuukiHirama** [comment]
descriptionを使わずString(x) を使用するように修正致しました。
f3901eb
