### ISSUE TITLE
UITableViewDelegate

### ISSUE THREAD

**Issue by rujiie** [YuukiHirama/Task0#5]
ViewControllerはUITableViewDelegateを実装していないので
UITableViewDelegateは記述しない方が良いと思います。
あと、できればですがプロトコルの実装部分には
//MARK: - UITableViewDataSource
　〜〜〜ここに実装処理
などと書いて貰えると見やすくなります。

**Comment by YuukiHirama** [comment]
不要な継承を削除し
コメントを修正致しました。
c7db30b

**Comment by rujiie** [comment]
確認しました、ありがとうございます。
